#! /bin/bash

#########################################
#		ALIASES			#
#########################################

# colorize ls output #
alias ls='ls --color=auto -F'
# remove unused dependencies #
alias killallorphans='sudo pacman -R $(pacman -Qtdq)'
# acronym for clear #
alias c='clear'
# pause between pings shortened #
alias fastping='ping -c 5 -i 0.002'
# snapshot manager
alias snapshot='sudo btrfs-assistant'
# reload font cache
alias reloadfontcache='fc-cache -fv' 
#yarn XDG_CONFIG_HOME
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
# vi vim nvim
alias vi='nvim'
alias vim='nvim'
# update pacman mirror
alias update-mirrorlist='sudo reflector --verbose --country Germany -l 5 --sort rate --save /etc/pacman.d/mirrorlist'

